// <auto-generated />
namespace Airlines.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class zmiany123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zmiany123));
        
        string IMigrationMetadata.Id
        {
            get { return "201710141305594_zmiany123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
